/* Generated by Together */

package model.brmodel;

import java.util.Date;
public class AggregationFactRule implements IParticipationFactRule {
    public AggregationFactRule(BusinessObject subject, BusinessObject actionObject) {
        this.setSubject(subject);
        this.setActionObject(actionObject);
        this.setName(subject.getName() + " COMPOSED OF " + actionObject.getName());
         this.timeStamp = new Date();
    }
@Override
public String toString() {	
	return this.getName();
}
    public BusinessObject getSubject() {
        return this.subject;
    }

    public void setSubject(BusinessObject subject) {
        this.subject = subject;
    }

    public BusinessObject getActionObject() {
        return this.actionObject;
    }

    public void setActionObject(BusinessObject actionObject) {
        this.actionObject = actionObject;
    }

    public String getName() {
        return this.name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public Date getTimeStamp(){
            return timeStamp;
        }

    	private BusinessObject subject=null;
    private BusinessObject actionObject=null;
    private String name=null;
    private Date timeStamp;
}
