package model.brmodel;
import java.util.Vector;
/* Generated by Together */

public class AndBlock implements BooleanBlock {
 public AndBlock(){
    this.block=new Vector(0);
 }
 public AndBlock(Object incoming) {
        this.block = new Vector(0);
        this.block.addElement(incoming);
    }

    public void addIncoming(Object incoming){
        this.block.addElement(incoming);
    }
@Override
public String toString() {
	// TODO Auto-generated method stub
	return getClassName()+" "+block.toString();
}

    public Vector getBlock(){ return block; }



    public String getClassName(){
            return className;
        }

    private Vector block;
    private final String className = "AndBlock";
	public void setBlock(Vector p_block) {
		this.block =p_block;
		
	}
}
