/* Generated by Together */

package model.brmodel;

import java.util.Date;
public class AssociationFactRule implements IParticipationFactRule {
    public AssociationFactRule(BusinessObject subject, BusinessObject actionObject, String action) {
        this.setSubject(subject);
        this.setActionObject(actionObject);
        this.action = action;
        this.setName(subject.getName() + ' ' + action + " BY " + actionObject.getName());
         this.timeStamp = new Date();
    }
@Override
public String toString() {
	// TODO Auto-generated method stub
	return getName();
	
}
    public String getAction() {
        return action;
    }

    public void setAction(String action) {
        this.action = action;
    }

    public BusinessObject getSubject() {
        return this.subject;
    }

    public void setSubject(BusinessObject subject) {
        this.subject = subject;
    }

    public BusinessObject getActionObject() {
        return this.actionObject;
    }

    public void setActionObject(BusinessObject actionObject) {
        this.actionObject = actionObject;
    }

    public String getName() {
        return this.name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public Date getTimeStamp(){
            return timeStamp;
        }

	private BusinessObject subject=null;
    private BusinessObject actionObject=null;
    private String name=null;
    private String action;
    private Date timeStamp;
}
