/* Generated by Together */
package model.brmodel;

import java.util.Vector;
import java.util.Date;

public class BusinessObject {
    public BusinessObject() {
		this.subClasses=new Vector();
        this.superClasses=new Vector();
        this.attributes=new Vector();
    	this.rolesOfThisObject=new Vector();
        this.objectsWithThisRole=new Vector();
        this.composedBy=new Vector();
        this.composes=new Vector();
        this.modifiedBy=new Vector();
        this.modifiedByVerbs=new Vector();
        this.modifies=new Vector();
        this.modifiesVerbs=new Vector();
        this.values=new Vector();
         this.timeStamp = new Date();
    }
@Override
public String toString() {
	return getName();
}
    public Vector getModifiedByVerbs(){ return modifiedByVerbs; }

    public void setModifiedByVerbs(Vector modifiedByVerbs){ this.modifiedByVerbs = modifiedByVerbs; }

    public String getName(){ return name; }

    public void setName(String name){ this.name = name; }

    public Vector getSubClasses(){ return subClasses; }

    public void setSubClasses(Vector subClasses){ this.subClasses = subClasses; }

    public Vector getSuperClasses(){ return superClasses; }

    public void setSuperClasses(Vector superClasses){ this.superClasses = superClasses; }



    public Vector getAttributes(){ return attributes; }

    public void setAttributes(Vector attributes){ this.attributes = attributes; }

    public Vector getValues(){ return values; }

    public void setValues(Vector values){ this.values = values; }

    public Vector getRolesOfThisObject(){
            return rolesOfThisObject;
        }

    public void setRolesOfThisObject(Vector rolesOfThisObject){
            this.rolesOfThisObject = rolesOfThisObject;
        }

    public Vector getObjectsWithThisRole(){
            return objectsWithThisRole;
        }

    public void setObjectsWithThisRole(Vector objectsWithThisRole){
            this.objectsWithThisRole = objectsWithThisRole;
        }

    public Vector getComposedBy(){ return composedBy; }

    public void setComposedBy(Vector composedBy){ this.composedBy = composedBy; }

    public Vector getComposes(){ return composes; }

    public void setComposes(Vector composes){ this.composes = composes; }

    public Vector getModifiedBy(){ return modifiedBy; }

    public void setModifiedBy(Vector modifiedBy){ this.modifiedBy = modifiedBy; }

    public Vector getModifies(){ return modifies; }

    public void setModifies(Vector modifies){ this.modifies = modifies; }

    public Vector getModifiesVerbs(){ return modifiesVerbs; }

    public void setModifiesVerbs(Vector modifiesVerbs){ this.modifiesVerbs = modifiesVerbs; }

    public Date getTimeStamp(){
            return timeStamp;
        }

    private Vector modifiedByVerbs;
    private String name="";
    private Vector subClasses;
    private Vector superClasses;

    private Vector attributes;
    private Vector values;
    private Vector rolesOfThisObject;
    private Vector objectsWithThisRole;
    private Vector composedBy;
    private Vector composes;
    private Vector modifiedBy;
    private Vector modifies;
    private Vector modifiesVerbs;
    private Date timeStamp;
}
