/* Generated by Together */

package model.brmodel;

import java.util.Date;
import java.util.Vector;

import model.ExpectedResult;
import model.Requirement;
import model.State;
public class BusinessAction {
    public BusinessAction() {
        description="";
         this.timeStamp = new Date();
    }

    public BusinessAction(String description) {
        this.description = description;
         this.timeStamp = new Date();
    }

    public String getDescription(){ return description; }
    @Override
    public String toString() {
    	return getDescription();
    }
    public void setDescription(String description){ this.description = description; }

    public Date getTimeStamp(){
            return timeStamp;
        }

    private String description;
    private Date timeStamp;
//HCanedo_17032007_begin
    private int state = State.POSITIVE.intValue();
    private int risklevel;
    private Vector requirement;
    private Vector<ExpectedResult> result;

	/**
	 * @return Returns the risklevel.
	 */
	public int getRisklevel() {
		return risklevel;
	}

	/**
	 * @param risklevel The risklevel to set.
	 */
	public void setRisklevel(int risklevel) {
		this.risklevel = risklevel;
	}

	/**
	 * @return Returns the state.
	 */
	public int getState() {
		return state;
	}

	/**
	 * @param state The state to set.
	 */
	public void setState(int state) {
		this.state = state;
	}
//	HCanedo_10032007_end

	public Vector<Requirement> getRequirement() {
		if (requirement == null)
			requirement = new Vector<Requirement>();
		return requirement;
	}

	public void setRequirement(Vector requirement) {
		this.requirement = requirement;
	}

	public Vector<ExpectedResult> getResult() {
		if (result == null)
			result = new Vector<ExpectedResult>();
		return result;
	}

	public void setResult(Vector result) {
		this.result = result;
	}


}
