/* Generated by Together */

package model.brmodel;
import java.util.Date;

public interface IFactRule {
    BusinessObject getSubject();

    void setSubject(BusinessObject subject);

    BusinessObject getActionObject();

    Date getTimeStamp();

    void setActionObject(BusinessObject actionObject);

    String getName();

    void setName(String name);
    

  
}
