/* Generated by Together */

package model.brmodel;

import java.util.Date;
public class MathematicalCalculationRule {
    public MathematicalCalculationRule() {
         this.timeStamp = new Date();
    }

    public String getSubjectExpression(){ return subjectExpression; }

    public void setSubjectExpression(String subjectExpression){ this.subjectExpression = subjectExpression; }

    public String getName(){ return name; }

    public void setName(String name){ this.name = name; }

    public BusinessObject getSubject(){ return subject; }

    public void setSubject(BusinessObject subject){ this.subject = subject; }

    public String getMathExpression(){ return mathExpression; }

    public void setMathExpression(String mathExpression){ this.mathExpression = mathExpression; }

    public Date getTimeStamp(){
            return timeStamp;
        }

    private String subjectExpression;
    private String name;
    private BusinessObject subject;
    private String mathExpression;
    private Date timeStamp;
}
