/* Generated by Together */

package model.brmodel;

public interface RelationalPair {
    
    public BusinessObject getTheObject();

    public void setTheObject(BusinessObject theObject);

    public String getTheValue();

    public void setTheValue(String theValue);

    public String getClassName();

}
