/* Generated by Together */

package bi.view.testdataviews;

import java.awt.Dimension;
import java.awt.Point;
import java.awt.Toolkit;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.util.ArrayList;
import java.util.List;

import javax.swing.JButton;
import javax.swing.JCheckBox;
import javax.swing.JLabel;
import javax.swing.JPanel;
import javax.swing.JScrollPane;
import javax.swing.JTextField;

import model.TestData;
import bi.view.lang.CMMessages;
import bi.view.mainframeviews.CMFrameView;
import bi.view.utils.CMJEditorPaneFocusChangeable;
import bi.view.utils.JCustomDialog;
public class CMDialogEditTestData extends JCustomDialog {
    public CMDialogEditTestData(CMFrameView p_CMFrameView, TestData p_TestData)
    {
        super(p_CMFrameView);
        m_CMFrameView=p_CMFrameView;
        m_TestData= p_TestData;
        m_testdataDescription = m_TestData.getDescription();
        initGUI();
    }
//hcanedo_21102004_begin
    public void initGUI()
    {
        setTitle(CMMessages.getString("TESTDATA_TITLE_DIALOG_EDIT_TESTDATA")); //$NON-NLS-1$
        setBounds(new java.awt.Rectangle(0,0,373,243));
        getContentPane().add(jPanelEditTestData, java.awt.BorderLayout.CENTER);
        jPanelEditTestData.setLayout(null);
        jPanelEditTestData.setPreferredSize(new java.awt.Dimension(481,277));
        jPanelEditTestData.add(jLabelName);
        jPanelEditTestData.add(jTextFieldName);
        jPanelEditTestData.add(jLabelTestCase);
        jPanelEditTestData.add(jCheckBoxSet);
        jPanelEditTestData.add(jTextFieldTestCase);
        jPanelEditTestData.add(jScrollPaneDescription);
        jPanelEditTestData.add(jButtonOk);
        jPanelEditTestData.add(jButtonCancel);
        jLabelName.setText(CMMessages.getString("TESTDATA_NAME_TESTDATA")); //$NON-NLS-1$
        jLabelName.setBounds(new java.awt.Rectangle(26, 24, 60, 16));
        jLabelName.setFont(new java.awt.Font("SansSerif", java.awt.Font.PLAIN, 11)); //$NON-NLS-1$
        jTextFieldName.setText(""); //$NON-NLS-1$
        jTextFieldName.setBounds(new java.awt.Rectangle(95, 22, 89, 20));
        jTextFieldName.setEditable(false);
        jLabelTestCase.setText(CMMessages.getString("TESTDATA_TESTCASE_IN_TESTDATA")); //$NON-NLS-1$
        jLabelTestCase.setBounds(new java.awt.Rectangle(26, 59, 99, 16));
        jLabelTestCase.setFont(new java.awt.Font("SansSerif", java.awt.Font.PLAIN, 11)); //$NON-NLS-1$
        jCheckBoxSet.setText(CMMessages.getString("TESTDATA_IS_SET_TESTDATA")); //$NON-NLS-1$
        jCheckBoxSet.setBounds(new java.awt.Rectangle(244, 20, 82, 24));
        jCheckBoxSet.setFont(new java.awt.Font("SansSerif", java.awt.Font.PLAIN, 11)); //$NON-NLS-1$
        jTextFieldTestCase.setText(""); //$NON-NLS-1$
        jTextFieldTestCase.setBounds(new java.awt.Rectangle(95, 57, 89, 20));
        jTextFieldTestCase.setEditable(false);
//$NON-NLS-1$
//$NON-NLS-1$
        jScrollPaneDescription.setBounds(new java.awt.Rectangle(26, 85, 319, 79));
        jScrollPaneDescription.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(),
        CMMessages.getString("TESTDATA_DESCRIPTION_TESTDATA"), javax.swing.border.TitledBorder.LEADING, javax.swing.border.TitledBorder.TOP, new java.awt.Font("SansSerif", 0, 11),
        new java.awt.Color(60, 60, 60)));
        jTextAreaDescription.setText(""); //$NON-NLS-1$
        jTextAreaDescription.setBounds(new java.awt.Rectangle(238,24,53,16));
        jScrollPaneDescription.getViewport().add(jTextAreaDescription);
        jButtonOk.setText(CMMessages.getString("BUTTON_OK")); //$NON-NLS-1$
        jButtonOk.setBounds(new java.awt.Rectangle(91, 175, 73, 27));
        jButtonCancel.setText(CMMessages.getString("BUTTON_CANCEL")); //$NON-NLS-1$
        jButtonCancel.setBounds(new java.awt.Rectangle(199, 175, 73, 27));
        jButtonOk.addActionListener(new ActionListener(){public void actionPerformed(ActionEvent e){jButtonOkActionPerformed(e);}});
        jButtonCancel.addActionListener(new ActionListener(){public void actionPerformed(ActionEvent e){jButtonCancelActionPerformed(e);}});
      	Dimension screenSize = Toolkit.getDefaultToolkit().getScreenSize();
    	Dimension dlgSize = this.getPreferredSize();
    	Point loc = getLocation();
    	this.setLocation((screenSize.width - dlgSize.width) / 2, (screenSize.height - dlgSize.height) / 2);
//hcanedo_21_09_2004_begin
    	setModal(true);
    	setResizable(false);
//hcanedo_21_09_2004_end
        jCheckBoxSet.setEnabled(false);
        charge();
//hcanedo_07102005_begin
        getRootPane().setDefaultButton(jButtonOk);
//hcanedo_07102005_end
    }
//hcanedo_21102004_end

	public void charge()
    {
        jTextFieldName.setText(m_TestData.getName());
        jTextFieldTestCase.setText(m_TestData.getM_TestCaseinTestData());
        jTextFieldTestCase.setSize(new java.awt.Dimension(89,20));
        jTextAreaDescription.setText(m_TestData.getDescription());
        jTextAreaDescription.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        jCheckBoxSet.setSelected(m_TestData.isSet());
    }
    public void jButtonOkActionPerformed(ActionEvent e)
    {
    	m_testdataDescription = jTextAreaDescription.getText();
        dispose();
    }

    public void jButtonCancelActionPerformed(ActionEvent e)
    {
        dispose();
    }

    private CMFrameView m_CMFrameView;
    private TestData m_TestData;
    private JPanel jPanelEditTestData = new JPanel();
    private JLabel jLabelName = new JLabel();
    private JTextField jTextFieldName = new JTextField();
    private JLabel jLabelTestCase = new JLabel();
    private JCheckBox jCheckBoxSet = new JCheckBox();
    private JTextField jTextFieldTestCase = new JTextField();
    private JScrollPane jScrollPaneDescription = new JScrollPane();
    private CMJEditorPaneFocusChangeable jTextAreaDescription = new CMJEditorPaneFocusChangeable();
    private JButton jButtonOk = new JButton();
    private JButton jButtonCancel = new JButton();
    public static String m_testdataDescription;
	protected List getOrder() {
		List focusOrder= new ArrayList();
		focusOrder.add(jTextAreaDescription);
		focusOrder.add(jButtonOk);
		focusOrder.add(jButtonCancel);
		return focusOrder;
	}
	protected void PressJButtonCancel(Object object) {
		jButtonCancelActionPerformed(null);
	}
	protected void PressJButtonOk(Object object) {
		jButtonOkActionPerformed(null);
	}
}
