/* Generated by Together */

package bi.view.testdataviews;

import java.awt.Dimension;

import java.awt.Toolkit;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.util.ArrayList;
import java.util.List;

import javax.swing.JButton;

import javax.swing.JLabel;
import javax.swing.JPanel;
import javax.swing.JScrollPane;

import javax.swing.JTextField;
import javax.swing.undo.UndoableEdit;

import model.BusinessRules;
import model.StructureTestData;
import model.edit.CMModelEditFactory;
import bi.view.lang.CMMessages;
import bi.view.mainframeviews.CMFrameView;
import bi.view.undomanagementviews.CMCompoundEdit;
import bi.view.utils.CMBaseJComboBox;
import bi.view.utils.CMJEditorPaneFocusChangeable;
import bi.view.utils.JCustomDialog;
@SuppressWarnings("serial")
public class CMDialogEditTDStructure extends JCustomDialog {
    public CMDialogEditTDStructure( CMFrameView p_CMFrameView, StructureTestData p_StructureTestData, UndoableEdit p_ce)
    {
    	
        	super(p_CMFrameView);
        	m_StructureTestData= p_StructureTestData;
            if(p_ce == null)
            	m_ce = new CMCompoundEdit();
            else
            	m_ce = (CMCompoundEdit) p_ce;
            initGUI();
    }

    public void initGUI()
    {
        setTitle(CMMessages.getString("TESTDATA_TITLE_DIALOG_EDIT_TDSTRUCTURE")); //$NON-NLS-1$
        setBounds(new java.awt.Rectangle(0, 0, 404, 236));
        getContentPane().add(jPanel1, java.awt.BorderLayout.CENTER);
        jPanel1.setLayout(null);
        jPanel1.setPreferredSize(new java.awt.Dimension(481,277));
        jPanel1.add(jTextFieldName);
        jPanel1.add(jComboBoxType);
        jPanel1.add(jLabelName);
        jPanel1.add(jLabelType);
//hcanedo_21102004_begin
//        jPanel1.add(jLabelDescription);
//hcanedo_21102004_end
        jPanel1.add(jScrollPaneDescription);
        jPanel1.add(jButtonOk);
        jPanel1.add(jButtonCancel);
        jTextFieldName.setText(""); //$NON-NLS-1$
        jTextFieldName.setBounds(new java.awt.Rectangle(71, 26, 81, 20));
        jTextFieldName.setEditable(false);
        jComboBoxType.setBounds(new java.awt.Rectangle(245, 26, 130, 21));
        jComboBoxType.addItem(BusinessRules.TYPETDSTRUCTURE_PRIMARY );
        jComboBoxType.addItem(BusinessRules.TYPETDSTRUCTURE_SECONDARY );
        jComboBoxType.addItem(BusinessRules.TYPETDSTRUCTURE_RESULT );
        jComboBoxType.setEditable(false);
        jLabelName.setText(CMMessages.getString("TESTDATA_NAME_TDSTRUCTURE")); //$NON-NLS-1$
        jLabelName.setBounds(new java.awt.Rectangle(23, 28, 50, 16));
//hcanedo_21102004_begin
        jLabelName.setFont(new java.awt.Font("SansSerif",java.awt.Font.PLAIN,11)); //$NON-NLS-1$
        jLabelType.setText(CMMessages.getString("TESTDATA_TYPE_TDSTRUCTURE")); //$NON-NLS-1$
        jLabelType.setBounds(new java.awt.Rectangle(192, 28, 41, 16));
        jLabelType.setFont(new java.awt.Font("SansSerif", java.awt.Font.PLAIN, 11)); //$NON-NLS-1$
/*        jLabelDescription.setText(CMMessages.getString("TESTDATA_DESCRIPTION_TDSTRUCTURE")); //$NON-NLS-1$
        jLabelDescription.setBounds(new java.awt.Rectangle(24, 74, 105, 16));
        jLabelDescription.setFont(new java.awt.Font("SansSerif", java.awt.Font.PLAIN, 11)); //$NON-NLS-1$*/
        jScrollPaneDescription.setBounds(new java.awt.Rectangle(23, 61, 354, 97));
        jScrollPaneDescription.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(
        new java.awt.Color(153, 153, 153), 1),CMMessages.getString("TESTDATA_DESCRIPTION_TDSTRUCTURE"), javax.swing.border.TitledBorder.LEADING, javax.swing.border.TitledBorder.TOP,
        new java.awt.Font("SansSerif", 0, 11), new java.awt.Color(60, 60, 60)));
        jTextAreaDescription.setBorder(javax.swing.BorderFactory.createEtchedBorder());
//hcanedo_21102004_end
        jTextAreaDescription.setText(""); //$NON-NLS-1$
        jTextAreaDescription.setBounds(new java.awt.Rectangle(274,28,53,16));
        jScrollPaneDescription.getViewport().add(jTextAreaDescription);
        jButtonOk.setText(CMMessages.getString("BUTTON_OK")); //$NON-NLS-1$
        jButtonOk.setBounds(new java.awt.Rectangle(105, 169, 73, 27));
        jButtonCancel.setText(CMMessages.getString("BUTTON_CANCEL")); //$NON-NLS-1$
        jButtonCancel.setBounds(new java.awt.Rectangle(214, 169, 73, 27));
        jButtonOk.addActionListener(new ActionListener(){public void actionPerformed(ActionEvent e){jButtonOkActionPerformed(e);}});
        jButtonCancel.addActionListener(new ActionListener(){public void actionPerformed(ActionEvent e){jButtonCancelActionPerformed(e);}});
        Dimension screenSize = Toolkit.getDefaultToolkit().getScreenSize();
    	Dimension dlgSize = this.getPreferredSize();
    	this.setLocation((screenSize.width - dlgSize.width) / 2, (screenSize.height - dlgSize.height) / 2);
    	setModal(true);
    	setResizable(false);
        charge();
//hcanedo_07102005_begin
        getRootPane().setDefaultButton(jButtonOk);
//hcanedo_07102005_end
    }
	public void charge()
    {
        jTextFieldName.setText(m_StructureTestData.getName());
        jTextAreaDescription.setText(m_StructureTestData.getDescription());
        jComboBoxType.setSelectedItem(m_StructureTestData.getType());
    }
    public void jButtonOkActionPerformed(ActionEvent e)
    {
    	m_ce.addEdit(CMModelEditFactory.INSTANCE.createChangeDescriptionInStructureTestData(m_StructureTestData,jTextAreaDescription.getText()));
        m_StructureTestData.setDescription(jTextAreaDescription.getText());
        m_ce.addEdit(CMModelEditFactory.INSTANCE.createChangeTypeInStructureTestData(m_StructureTestData,jComboBoxType.getSelectedItem().toString()));
        m_StructureTestData.setType(jComboBoxType.getSelectedItem().toString());
        isOk = true;
        dispose();
    }

    public void jButtonCancelActionPerformed(ActionEvent e)
    {
    	isOk = false;
        dispose();
    }

    private StructureTestData m_StructureTestData;
    private JPanel jPanel1 = new JPanel();
    private JTextField jTextFieldName = new JTextField();
    private CMBaseJComboBox jComboBoxType = new CMBaseJComboBox(this);
    private JLabel jLabelName = new JLabel();
    private JLabel jLabelType = new JLabel();
    private JScrollPane jScrollPaneDescription = new JScrollPane();
    private CMJEditorPaneFocusChangeable jTextAreaDescription = new CMJEditorPaneFocusChangeable();
    private JButton jButtonOk = new JButton();
    private JButton jButtonCancel = new JButton();
    public static boolean isOk = false;
    private CMCompoundEdit m_ce;
	@SuppressWarnings("unchecked")
	protected List getOrder() {
		List focusOrder=new ArrayList();
		focusOrder.add(jComboBoxType);
		focusOrder.add(jTextAreaDescription);
		focusOrder.add(jButtonOk);
		focusOrder.add(jButtonCancel);
		return focusOrder;
	}

	protected void PressJButtonCancel(Object object) {
		jButtonCancelActionPerformed(null);
	}

	protected void PressJButtonOk(Object object) {
		jButtonOkActionPerformed(null);
	}
}
