/* Generated by Together */

package bi.view.testdataviews;

import java.awt.Dimension;
import java.awt.Point;
import java.awt.Toolkit;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.util.ArrayList;
import java.util.List;

import javax.swing.JButton;
import javax.swing.JComponent;
import javax.swing.JFormattedTextField;
import javax.swing.JLabel;
import javax.swing.JPanel;
import javax.swing.JScrollPane;
import javax.swing.JSpinner;
import javax.swing.JTextField;
import javax.swing.SpinnerModel;
import javax.swing.SpinnerNumberModel;
import javax.swing.event.ChangeEvent;
import javax.swing.event.ChangeListener;

import model.BusinessRules;
import model.StructureTestData;
import bi.view.lang.CMMessages;
import bi.view.mainframeviews.CMFrameView;
import bi.view.utils.CMBaseJComboBox;
import bi.view.utils.CMJEditorPaneFocusChangeable;
import bi.view.utils.JCustomDialog;

public class CMDialogCreateStructure extends JCustomDialog {
    public CMDialogCreateStructure(CMFrameView p_FrameView, StructureTestData p_StructureTestData,CMGridTDStructure p_gridTDStructure)
    {
        super(p_FrameView);
        m_FrameView=p_FrameView;
        m_StructureTestData=p_StructureTestData;
        m_CMGridTDStructure = p_gridTDStructure;
        initGUI();
    }
    public void initGUI()
    {
    	CMDialogCreateStructure.m_cantRows = 0;
        jPanel1.setLayout(null);
        jPanel1.setPreferredSize(new java.awt.Dimension(481,277));
        jPanel1.setToolTipText(""); //$NON-NLS-1$
        jPanel1.setBorder(null);
        jPanel1.add(jLabelChoose);
        jPanel1.add(jComboBoxChooser);
        jPanel1.add(jLabelName);
        jPanel1.add(jTextFieldName);
        jPanel1.add(jLabeldescription);
        jPanel1.add(scrollDescriptions);
        jPanel1.add(jButtonOk);
        jPanel1.add(jButtonCancel);
        jPanel1.add(jLabelType);
        jPanel1.add(jSpinnerRows);
        scrollDescriptions.getViewport().add(jTextAreaDescription);
      /*  jPanel1.add(jTextFieldRows);
        jPanel1.add(jScrollBarRows);*/
        jLabelChoose.setText(CMMessages.getString("TESTDATA_CHOOSE_NUM_ROWS_STRUCTURE")); //$NON-NLS-1$
        jLabelChoose.setBounds(new java.awt.Rectangle(23, 28, 227, 16));
        jLabelChoose.setFont(new java.awt.Font("SansSerif",java.awt.Font.BOLD,11)); //$NON-NLS-1$
//hcanedo_21_09_2004_begin
        jComboBoxChooser.setBounds(new java.awt.Rectangle(95, 64, 255, 25));
        jComboBoxChooser.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jComboBoxChooser.setMinimumSize(new java.awt.Dimension(130,18));
        jComboBoxChooser.setMaximumSize(new java.awt.Dimension(32767,18));
        jComboBoxChooser.setPreferredSize(new java.awt.Dimension(134,18));
        jComboBoxChooser.setSize(new java.awt.Dimension(257, 22));
//hcanedo_21_09_2004_end
        jLabelName.setText(CMMessages.getString("TESTDATA_NAME_STRUCTURE")); //$NON-NLS-1$
        jLabelName.setBounds(new java.awt.Rectangle(25, 101, 54, 16));
        jLabelName.setFont(new java.awt.Font("SansSerif",java.awt.Font.BOLD,11)); //$NON-NLS-1$
        jTextFieldName.setText(m_StructureTestData.getName());
        jTextFieldName.setBounds(new java.awt.Rectangle(94, 100, 257, 20));
        jTextFieldName.setEditable(false);
        jLabeldescription.setText(CMMessages.getString("TESTDATA_DESCRIPTION_STRUCTURE")); //$NON-NLS-1$
        jLabeldescription.setBounds(new java.awt.Rectangle(22, 136, 144, 16));
        jLabeldescription.setFont(new java.awt.Font("SansSerif",java.awt.Font.BOLD,11)); //$NON-NLS-1$
        jTextAreaDescription.setText(m_StructureTestData.getDescription());
        scrollDescriptions.setBounds(new java.awt.Rectangle(24, 162, 329, 55));
        scrollDescriptions.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));
     //   jTextAreaDescription.setLineWrap(true);
       // jTextAreaDescription.setWrapStyleWord(true);
        jButtonOk.setText(CMMessages.getString("BUTTON_OK")); //$NON-NLS-1$
        jButtonOk.setBounds(new java.awt.Rectangle(91, 235, 73, 27));
        jButtonCancel.setText(CMMessages.getString("BUTTON_CANCEL")); //$NON-NLS-1$
        jButtonCancel.setBounds(new java.awt.Rectangle(215, 236, 73, 27));
        jButtonOk.addActionListener(new ActionListener(){public void actionPerformed(ActionEvent e){jButtonOkActionPerformed(e);}});
        jButtonCancel.addActionListener(new ActionListener(){public void actionPerformed(ActionEvent e){jButtonCancelActionPerformed(e);}});
        jLabelType.setText(CMMessages.getString("TESTDATA_TYPE_STRUCTURE")); //$NON-NLS-1$
        jLabelType.setBounds(new java.awt.Rectangle(27, 64, 42, 16));
        jLabelType.setFont(new java.awt.Font("SansSerif",java.awt.Font.BOLD,11)); //$NON-NLS-1$
//hcanedo_21_09_2004_begin
        jSpinnerRows.setBounds(new java.awt.Rectangle(277, 22, 70,20));
//hcanedo_21_09_2004_end
        jSpinnerRows.setEditor(new JSpinner.NumberEditor(jSpinnerRows));

        ftf = getTextField(jSpinnerRows);
        if (ftf != null ) {
            ftf.setColumns(8); //specify more width than we need
            ftf.setHorizontalAlignment(JTextField.RIGHT);
            ftf.setEditable(false);
            ftf.setBackground(new java.awt.Color(255,255,255));
        }/*
        jTextFieldRows.setText(CMMessages.getString("TESTDATA_1_10")); //$NON-NLS-1$
        jTextFieldRows.setBounds(new java.awt.Rectangle(277, 22, 54, 24));
        jScrollBarRows.setBounds(new java.awt.Rectangle(331, 22, 16, 24));
        jScrollBarRows.setMaximum(200);
        jScrollBarRows.setMinimum(1);
        jScrollBarRows.setValue(0);
        jScrollBarRows.setToolTipText(""); //$NON-NLS-1$*/
        jComboBoxChooser.addItem(BusinessRules.TYPETDSTRUCTURE_PRIMARY);
        jComboBoxChooser.addItem(BusinessRules.TYPETDSTRUCTURE_SECONDARY);
        jComboBoxChooser.addItem(BusinessRules.TYPETDSTRUCTURE_RESULT);
       // jScrollBarRows.addAdjustmentListener(new AdjustmentListener(){public void adjustmentValueChanged(AdjustmentEvent e){jScrollBarRowsAdjustmentValueChanged(e);}});
        setTitle(CMMessages.getString("TESTDATA_TITLE_DIALOG_CREATE_STRUCTURE")); //$NON-NLS-1$
        setBounds(new java.awt.Rectangle(0,0,408,300));
        getContentPane().setLayout(new java.awt.BorderLayout());
        getContentPane().add(jPanel1, java.awt.BorderLayout.CENTER);
        Dimension screenSize = Toolkit.getDefaultToolkit().getScreenSize();
    	Dimension dlgSize = this.getPreferredSize();
    	Point loc = getLocation();
    	this.setLocation((screenSize.width - dlgSize.width) / 2 /*+ loc.x*/, (screenSize.height - dlgSize.height) / 2 /*+ loc.y*/);
//hcanedo_21_09_2004_begin
    	setResizable(false);
    	setModal(true);
//hcanedo_21_09_2004_end
      /*  jScrollBarRows.enable();
        jTextFieldRows.addActionListener(new ActionListener(){public void actionPerformed(ActionEvent e){jTextFieldRowsActionPerformed(e);}});*/
        jSpinnerRows.addChangeListener(new ChangeListener(){public void stateChanged(ChangeEvent e){jSpinnerRowsChangeEvent(e);}} );
        getRootPane().setDefaultButton(jButtonOk);
    }

	 public JFormattedTextField getTextField(JSpinner spinner) {
        JComponent editor = spinner.getEditor();
        if (editor instanceof JSpinner.NumberEditor) {
            return ((JSpinner.NumberEditor)editor).getTextField();
        } else {
            System.err.println("Unexpected editor type: "
                               + spinner.getEditor().getClass()
                               + " isn't a descendant of DefaultEditor");
            return null;
        }
    }

      public void jSpinnerRowsChangeEvent(ChangeEvent e) {
        SpinnerModel numberModel = jSpinnerRows.getModel();
        if (numberModel instanceof SpinnerNumberModel) {
		//	jSpinnerRows.getValue().toString();
        }
    }


    public void jButtonOkActionPerformed(ActionEvent e)
    {
		m_StructureTestData.setDescription(jTextAreaDescription.getText());
        m_StructureTestData.setName(jTextFieldName.getText());
        m_StructureTestData.setType(jComboBoxChooser.getSelectedItem().toString());
        CMDialogCreateStructure.m_cantRows = Integer.parseInt(jSpinnerRows.getValue().toString());
        dispose();
    }

    public void jButtonCancelActionPerformed(ActionEvent e)
    {
        m_CMGridTDStructure.getTDStructure().deleteIdStructure(m_StructureTestData.getId());
		dispose();
    }

/*    public void jScrollBarRowsAdjustmentValueChanged(AdjustmentEvent e)
    {
        jTextFieldRows.setText(Integer.toString(e.getValue()));
    }

    public void jTextFieldRowsActionPerformed(ActionEvent e)
    {
        jScrollBarRows.setValue(Integer.parseInt(jTextFieldRows.getText()));
    }*/

    private JPanel jPanel1 = new JPanel();
    private JLabel jLabelChoose = new JLabel();
    private CMBaseJComboBox jComboBoxChooser = new CMBaseJComboBox(this);
    private JLabel jLabelName = new JLabel();
    private JTextField jTextFieldName = new JTextField();
    private JLabel jLabeldescription = new JLabel();
    private CMJEditorPaneFocusChangeable jTextAreaDescription = new CMJEditorPaneFocusChangeable();
    private JButton jButtonOk = new JButton();
    private JButton jButtonCancel = new JButton();
    private CMFrameView m_FrameView;
    private StructureTestData m_StructureTestData;
    private CMGridTDStructure m_CMGridTDStructure;
    private JLabel jLabelType = new JLabel();
    private JScrollPane scrollDescriptions= new JScrollPane();
    public static int m_cantRows = 0;
   // private JTextField jTextFieldRows = new JTextField();
   // private JScrollBar jScrollBarRows = new JScrollBar();
    Integer value = new Integer(1);
 	Integer min = new Integer(1);
	Integer max = new Integer(200);
	Integer step = new Integer(1);
    SpinnerNumberModel model = new SpinnerNumberModel(value, min, max, step);

    JSpinner jSpinnerRows= new JSpinner(model);
    JFormattedTextField ftf = null;
	protected List getOrder() {
		List focusOrder= new ArrayList();
		focusOrder.add(jSpinnerRows);
		focusOrder.add(jComboBoxChooser);
		focusOrder.add(jTextAreaDescription);
		focusOrder.add(jButtonOk);
		focusOrder.add(jButtonCancel);
		return focusOrder;
	}
	protected void PressJButtonCancel(Object object) {
		jButtonCancelActionPerformed(null);

	}
	protected void PressJButtonOk(Object object) {
		jButtonOkActionPerformed(null);

	}
}
