/* Generated by Together */

package bi.view.testdataviews;

import java.awt.Dimension;
import java.awt.Point;
import java.awt.Toolkit;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.util.ArrayList;
import java.util.List;
import java.util.Vector;

import javax.swing.JButton;
import javax.swing.JLabel;
import javax.swing.JList;
import javax.swing.JPanel;
import javax.swing.JScrollPane;
import javax.swing.JTextArea;
import javax.swing.JTextField;
import javax.swing.event.ListSelectionEvent;
import javax.swing.event.ListSelectionListener;

import model.Project2;
import model.TestDataFormat;
import model.Variable;
import model.Variables;
import bi.view.lang.CMMessages;
import bi.view.mainframeviews.CMFrameView;
import bi.view.utils.JCustomDialog;
public class CMDialogAddVariable extends JCustomDialog {
    public CMDialogAddVariable(CMFrameView frame, CMGridTDStructure grid)
   {
        super(frame);
        m_Frame = frame;
        m_GridTDStructure = grid;
        try
        {
      		initGUI();
      		pack();
    	}
    	catch(Exception ex)
    	{
      		ex.printStackTrace();
    	}
    }
//hcanedo_21102004_begin
    public void initGUI()
    {
        jButtonCancel.setText(CMMessages.getString("BUTTON_CANCEL"));
        jButtonCancel.setBounds(new java.awt.Rectangle(382, 270, 73, 27));
        jButtonCancel.setMaximumSize(new java.awt.Dimension(79,25));
        jButtonCancel.setMinimumSize(new java.awt.Dimension(79,25));
        jButtonCancel.setPreferredSize(new java.awt.Dimension(79,25));
        jButtonCancel.addActionListener(new ActionListener(){public void actionPerformed(ActionEvent e){jButtonCancelActionPerformed(e);}});
        jButtonOk.setText(CMMessages.getString("BUTTON_OK"));
        jButtonOk.setBounds(new java.awt.Rectangle(291, 270, 73, 27));
        jButtonOk.setMaximumSize(new java.awt.Dimension(79,25));
        jButtonOk.setMinimumSize(new java.awt.Dimension(79,25));
        jButtonOk.setPreferredSize(new java.awt.Dimension(79,25));
        jButtonOk.addActionListener(new ActionListener(){public void actionPerformed(ActionEvent e){jButtonOkActionPerformed(e);}});
        jPanelButtons.setBounds(new java.awt.Rectangle(2, 326, 483, 39));
        jPanelButtons.add(jButtonOk);
        jPanelButtons.add(jButtonCancel);
        jScrollPaneDescriptionVariables.setBounds(new java.awt.Rectangle(15, 132, 248, 136));
        jScrollPaneDescriptionVariables.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(
        new java.awt.Color(153, 153, 153), 1),
        CMMessages.getString("TESTDATA_DESCRIPTION_TDSTRUCTURE"), javax.swing.border.TitledBorder.LEADING, javax.swing.border.TitledBorder.TOP, //$NON-NLS-1$
        new java.awt.Font("SansSerif", 0, 11), new java.awt.Color(60, 60, 60)));
        jScrollPaneNamesVariables.setBounds(new java.awt.Rectangle(13, 23, 163, 282));
        jScrollPaneNamesVariables.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(
        new java.awt.Color(153, 153, 153), 1),CMMessages.getString("TESTDATA_AVAILABLES_VARIABLES")
        , javax.swing.border.TitledBorder.LEADING, javax.swing.border.TitledBorder.TOP, //$NON-NLS-1$
        new java.awt.Font("SansSerif", 0, 11), new java.awt.Color(60, 60, 60))); //$NON-NLS-1$
//$NON-NLS-1$
//$NON-NLS-1$
        setTitle(CMMessages.getString("TESTDATA_TITLE_DIALOG_ADD_VARIABLES")); //$NON-NLS-1$
        setBounds(new java.awt.Rectangle(0, 0, 485, 394));
        getContentPane().setLayout(new java.awt.BorderLayout());
        getContentPane().setSize(new java.awt.Dimension(491,394));
        getContentPane().add(jPanelButtons, java.awt.BorderLayout.SOUTH);
        getContentPane().add(jPanelDialog, java.awt.BorderLayout.CENTER);
        jScrollPaneNamesVariables.getViewport().add(jListNamesVariables);
        jListNamesVariables.setBounds(new java.awt.Rectangle(244,50,32,32));
        jListNamesVariables.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        jTextAreaDescriptionVariables.setText(""); //$NON-NLS-1$
        jTextAreaDescriptionVariables.setBounds(new java.awt.Rectangle(150,20,53,16));
        jTextAreaDescriptionVariables.setBackground(new java.awt.Color(212,208,200));
        jTextAreaDescriptionVariables.setWrapStyleWord(true);
        jTextAreaDescriptionVariables.setLineWrap(true);
        jTextAreaDescriptionVariables.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        jScrollPaneDescriptionVariables.getViewport().add(jTextAreaDescriptionVariables);
        jListNamesVariables.addListSelectionListener(new ListSelectionListener(){public void valueChanged(ListSelectionEvent e){jListNamesVariablesValueChanged(e);}});
        jPanelDialog.setLayout(null);
        jPanelDialog.setPreferredSize(new java.awt.Dimension(487,327));
        jPanelDialog.add(jScrollPaneNamesVariables);
        jPanelDialog.add(jPanelDescription);
         Dimension screenSize = Toolkit.getDefaultToolkit().getScreenSize();
    	Dimension dlgSize = this.getPreferredSize();
    	Point loc = getLocation();
    	this.setLocation((screenSize.width - dlgSize.width) / 2, (screenSize.height - dlgSize.height) / 2);
    	setModal(true);
    	setResizable(false);
    	jPanelDescription.setBounds(new java.awt.Rectangle(192, 23, 278, 282));
    	jPanelDescription.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(),
        CMMessages.getString("TESTDATA_DESCRIPTION_VARIABLES"), javax.swing.border.TitledBorder.LEADING, javax.swing.border.TitledBorder.TOP, new java.awt.Font("SansSerif", 0, 11),
        new java.awt.Color(60, 60, 60)));
    	jPanelDescription.setLayout(null);
    	jPanelDescription.add(jScrollPaneDescriptionVariables);
    	jPanelDescription.add(jTextFieldValue);
    	jPanelDescription.add(jTextFieldType);
    	jPanelDescription.add(jTextFieldFormat);
    	jPanelDescription.add(jLabelValue);
    	jPanelDescription.add(jLabelType);
    	jPanelDescription.add(jLabelFormat);
    	jTextFieldValue.setText("");
    	jTextFieldValue.setBounds(new java.awt.Rectangle(84, 26, 177, 20));
    	jTextFieldValue.setEditable(false);
    	jTextFieldType.setText("");
    	jTextFieldType.setBounds(new java.awt.Rectangle(84, 62, 177, 20));
    	jTextFieldType.setEditable(false);
    	jTextFieldFormat.setText("");
    	jTextFieldFormat.setBounds(new java.awt.Rectangle(84, 98, 177, 20));
    	jTextFieldFormat.setEditable(false);
    	jLabelValue.setText(CMMessages.getString("TESTDATA_VALUE")); //$NON-NLS-1$
    	jLabelValue.setBounds(new java.awt.Rectangle(17, 28, 68, 16));
    	jLabelType.setText(CMMessages.getString("TESTDATA_TYPE")); //$NON-NLS-1$
    	jLabelType.setBounds(new java.awt.Rectangle(17, 64, 68, 16));
    	jLabelFormat.setText(CMMessages.getString("TESTDATA_FORMAT")); //$NON-NLS-1$
    	jLabelFormat.setBounds(new java.awt.Rectangle(17, 100, 68, 16));
//hcanedo_06102005_begin
    	jTextAreaDescriptionVariables.setEditable(false);
    	getRootPane().setDefaultButton(jButtonOk);

//hcanedo_06102005_end
    }
//hcanedo_21102004_end
    void close()
    {
    	dispose();
  	}
//hcanedo_21102004_begin
    private Vector getVariablesNames(Variables p_Variables){
    	Vector result= new Vector();
    	for(int i =0; i< p_Variables.getVariables().size();i++){
    		result.addElement(((Variable)p_Variables.getVariables().elementAt(i)).getM_Name());
    	}
    	return result;
    }
	public void charge()
    {
        m_Variables=m_Frame.getGridTDStructure().getTDStructure().getM_Variables();//svonborries_06012006
        if(m_Variables.getVariables().size()!=0)//getNames().size()!=0)
        {
        	jListNamesVariables.setListData(getVariablesNames(m_Variables));//m_Variables.getNames());
        	jListNamesVariables.setSelectedIndex(0);
        	try {
				//jTextFieldValue.setText(((Variable)m_Variables.getVariables().firstElement()).getM_Value().getValue().toString());
        		jTextFieldValue.setText(((Variable)m_Variables.getVariables().firstElement()).getFormattedValue());
			} catch (Exception e) {
				// TODO Auto-generated catch block
				e.printStackTrace();
			}
            jTextFieldType.setText(((Variable)m_Variables.getVariables().firstElement()).getM_Type());//(m_Variables.getType().elementAt(0)).toString()); //$NON-NLS-1$
            jTextFieldFormat.setText(((Variable)m_Variables.getVariables().firstElement()).getFormat());//(m_Variables.getFormat().elementAt(0)).toString()); //$NON-NLS-1$
        	jTextAreaDescriptionVariables.setText(((Variable)m_Variables.getVariables().firstElement()).getM_Description());//(m_Variables.getDescription().elementAt(0)).toString()); //$NON-NLS-1$ //$NON-NLS-2$
        	//currentFormat=((Variable)m_Variables.getVariables().firstElement()).getM_Formatter();//(TestDataFormat)m_Variables.getFormatter().elementAt(0);
        }
        else
        {
        	jListNamesVariables.setListData(getVariablesNames(m_Variables));//m_Variables.getNames());
        	jListNamesVariables.setSelectedIndex(-1);
        	jTextFieldValue.setText(""); //$NON-NLS-1$
            jTextFieldType.setText(""); //$NON-NLS-1$
            jTextFieldFormat.setText(""); //$NON-NLS-1$
        	jTextAreaDescriptionVariables.setText(""); //$NON-NLS-1$
        }

    }
    public void jListNamesVariablesValueChanged(ListSelectionEvent e)
    {
				int selectedIndex = jListNamesVariables.getSelectedIndex();
	            if(selectedIndex != -1)
            	{
            		try {
						//jTextFieldValue.setText(((Variable)m_Variables.getVariables().elementAt(selectedIndex)).getM_Value().getValue().toString());
            			jTextFieldValue.setText(((Variable)m_Variables.getVariables().elementAt(selectedIndex)).getFormattedValue());
					} catch (Exception e1) {

					}
                	jTextFieldType.setText(((Variable)m_Variables.getVariables().elementAt(selectedIndex)).getM_Type());//(m_Variables.getType().elementAt(selectedIndex)).toString()); //$NON-NLS-1$
	            	jTextFieldFormat.setText(((Variable)m_Variables.getVariables().elementAt(selectedIndex)).getFormat());//(m_Variables.getFormat().elementAt(selectedIndex)).toString()); //$NON-NLS-1$
        			jTextAreaDescriptionVariables.setText(((Variable)m_Variables.getVariables().elementAt(selectedIndex)).getM_Description());//(m_Variables.getDescription().elementAt(selectedIndex)).toString()); //$NON-NLS-1$ //$NON-NLS-2$
        			//currentFormat=((Variable)m_Variables.getVariables().elementAt(selectedIndex)).getM_Formatter();//(TestDataFormat)m_Variables.getFormatter().elementAt(selectedIndex);
            	}
        }
//hcanedo_21102004_end
    public void jButtonOkActionPerformed(ActionEvent e) {
        try
        {
        	int index=jListNamesVariables.getSelectedIndex();
        	Variable variable=((Variable)m_Variables.getVariables().elementAt(index));
        	String name=variable.getM_Name();
        	//String value=variable.getM_Value().getValue().toString();
        	String value=variable.getFormattedValue();
        	String type=variable.getM_Type();
        	String format=variable.getFormat();
        	TestDataFormat formatter=variable.getFormatter();
			m_GridTDStructure.setVariable(name,value,type,format,formatter,variable,null);
        	close();
        }
        catch(Exception ex)
        {
                close();
        }
    }

    public void jButtonCancelActionPerformed(ActionEvent e)
    {
		close();
    }

    public Project2 getM_Project()
    {
        return m_Project;
    }

    public void setM_Project(Project2 m_Project)
    {
        this.m_Project = m_Project;
    }

    private JButton jButtonCancel = new JButton();
    private JScrollPane jScrollPaneDescriptionVariables = new JScrollPane();
    private JScrollPane jScrollPaneNamesVariables = new JScrollPane();
    private JList jListNamesVariables = new JList();
    private JTextArea jTextAreaDescriptionVariables = new JTextArea();
    private CMFrameView m_Frame;
    private CMGridTDStructure m_GridTDStructure;
    private Variables m_Variables;
    private Project2 m_Project;
    private JPanel jPanelDialog = new JPanel();
    private JButton jButtonOk = new JButton();
    private JPanel jPanelButtons = new JPanel();
    private JPanel jPanelDescription = new JPanel();
    private JTextField jTextFieldValue = new JTextField();
    private JTextField jTextFieldType = new JTextField();
    private JTextField jTextFieldFormat = new JTextField();
    private JLabel jLabelValue = new JLabel();
    private JLabel jLabelType = new JLabel();
    private JLabel jLabelFormat = new JLabel();
//hcanedo_06102005_begin
	protected void PressJButtonCancel(Object object) {
		jButtonCancelActionPerformed(null);

	}
	protected void PressJButtonOk(Object object) {
		jButtonOkActionPerformed(null);

	}
//hcanedo_06102005_end
	protected List getOrder() {
		List focusOrder= new ArrayList();
		focusOrder.add(jListNamesVariables);
		focusOrder.add(jButtonOk);
		focusOrder.add(jButtonCancel);
		return focusOrder;
	}
}
