/* Generated by Together */

package bi.view.testdataviews;
import bi.controller.TDStructureManager;

public class CMIndexTDStructureUpdate {
protected CMIndexTDStructureUpdate(){}

    public static CMIndexTDStructureUpdate getInstance(){
              return instance;
        }
	public int getIndex()
    {

        return index;
    }
    public void setindex(int i)
    {
        if( i >= 0 ){
            index=i;}
    }

    public int getindexTestData(){
            return indexTestData;
        }

    public void setindexTestData(int indexTestData){
            this.indexTestData =indexTestData;
        }

    public int getnumOfTable(){
            return numOfTable;
        }

    public void setnumOfTable(int p_numoftable){
            this.numOfTable = p_numoftable;
        }

    public int getnumOfRow(){
            return numOfRow;
        }

    public void setnumOfRow(int p_numofrow){
            this.numOfRow = p_numofrow;
        }

    public int getnumOfCol(){
            return numOfCol;
        }

    public void setnumOfCol(int p_numofcol){
            this.numOfCol = p_numofcol;
        }

    public int getindexTestDataSet(){
            return indexTestDataSet;
        }

    public void setindexTestDataSet(int p_IndexTestDataSet){
            this.indexTestDataSet = p_IndexTestDataSet;
        }
    public void initIndex()
    {
        index=0;
        indexTestData=0;
        indexTestDataSet=0;
        indexActual=0;
		indexTarget=0;
		indexTestDataActual=0;
		indexTestDataTarget=0;
		indexTestDataSetActual=0;
		indexTestDataSetTarget=0;
    }
  	public void setState(boolean p_state)
  {
    state=p_state;
  }
  public boolean getState()
  {
    return state;
  }

    public TDStructureManager  getTDStructureManager(){
            return tdStructureManager;
        }

    public void setTDStructureManager(TDStructureManager tdStructureManager){
            this.tdStructureManager = tdStructureManager;
        }

   public int  getindexActual(){
            return indexActual;
        }

    public void setindexActual(int indexActual){
            this.indexActual = indexActual;
        }

   public int  getindexTestDataActual(){
            return indexTestDataActual;
        }

    public void setindexTestDataActual(int indexTestDataActual){
            this.indexTestDataActual = indexTestDataActual;
        }
  public int  getindexTestDataSetActual(){
            return indexTestDataSetActual;
        }

    public void setindexTestDataSetActual(int indexTestDataSetActual){
            this.indexTestDataSetActual = indexTestDataSetActual;
        }

       public int  getindexTarget(){
            return indexTarget;
        }

    public void setindexTarget(int indexTarget){
            this.indexTarget = indexTarget;
        }

   public int  getindexTestDataTarget(){
            return indexTestDataTarget;
        }

    public void setindexTestDataTarget(int indexTestDataTarget){
            this.indexTestDataTarget = indexTestDataTarget;
        }
  public int  getindexTestDataSetTarget(){
            return indexTestDataSetTarget;
        }

    public void setindexTestDataSetTarget(int indexTestDataSetTarget){
            this.indexTestDataSetTarget = indexTestDataSetTarget;
        }
    /**
     * @link
     * @shapeType PatternLink
     * @pattern Singleton
     * @supplierRole Singleton factory 
     */
    /*# private CMIndexTDStructureUpdate _cmIndexTDStructureUpdate; */
    private static CMIndexTDStructureUpdate instance =  new CMIndexTDStructureUpdate();
    private int index=0;
    private int indexTestData=0;
    private int numOfTable;
    private int numOfRow;
    private int numOfCol;
    private int indexTestDataSet=0;
    private boolean state=true;
    private TDStructureManager tdStructureManager;
    private int indexActual=0;
    private int indexTarget=0;
    private int indexTestDataActual=0;
    private int indexTestDataTarget=0;
    private int indexTestDataSetActual=0;
    private int indexTestDataSetTarget=0;
    private int rowOfGrid=0;
	/**
	 * @return Returns the rowOfGrid.
	 */
	public int getRowOfGrid() {
		return rowOfGrid;
	}
	/**
	 * @param rowOfGrid The rowOfGrid to set.
	 */
	public void setRowOfGrid(int rowOfGrid) {
		this.rowOfGrid = rowOfGrid;
	}
}
