/* Generated by Together */

package bi.view.testdataviews;

import java.awt.Color;
import java.awt.Font;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;

import javax.swing.BorderFactory;
import javax.swing.JScrollPane;
import javax.swing.JViewport;

import model.TDStructure;
import bi.view.mainframeviews.CMFrameView;

import com.eliad.swing.JSmartGrid;
import com.eliad.swing.JSmartGridHeader;
public class CMScrollpaneStructureDescription extends JScrollPane {
    public CMScrollpaneStructureDescription(CMFrameView p_Frame) {
        	m_Frame = p_Frame;
            initGUI();
    }
    public void initGUI(){
        m_cmStructureView = new CMStructureView(m_Frame);
        this.setViewportView(m_cmStructureView);
        //this.setAutoscrolls(true);
		m_cmStructureView.getViewport1().setScrollMode(JViewport.BACKINGSTORE_SCROLL_MODE);//harold canedo Lopez
        m_CMStructureHeaderView = new CMStructureHeaderView(m_cmStructureView);
      m_GridHeader = new JSmartGridHeader(m_cmStructureView,JSmartGrid.HORIZONTAL,m_CMStructureHeaderView,null,new CMStyleModelHeader());
       //m_GridHeader.setColumnAutoResizeMode(JSmartGridHeader.AUTO_RESIZE_NEXT);
      m_GridHeader.setColumnWidth(0,100);
      m_GridHeader.setColumnWidth(1,100);
      m_GridHeader.setColumnWidth(2,600);//1080);
      m_GridHeader.setColumnAutoResizeMode(JSmartGridHeader.AUTO_RESIZE_ALL);//AUTO_RESIZE_LAST
      m_GridHeader.setBackground(new Color(36,38,116));
      m_GridHeader.setSelectionBackgroundColor(new Color(36,38,116));
      m_GridHeader.setSelectionForegroundColor(new Color(252,254,252));
      m_GridHeader.setGridColor(new Color(196,194,196));
      m_GridHeader.setFont(new Font("Dialog",Font.PLAIN,12)); //$NON-NLS-1$
      m_GridHeader.setForeground(new Color(252,254,252));
      m_GridHeader.setBorder(BorderFactory.createRaisedBevelBorder());
      m_GridHeader.setRowResizable(false);
      m_cmStructureView.setColumnHeader(m_GridHeader);
//hcanedo_21_09_2004_begin
      addMouseListener(new MouseAdapter(){public void mouseClicked(MouseEvent e){thisMouseClicked(e);}});
      m_GridHeader.addMouseListener(new MouseAdapter(){public void mouseClicked(MouseEvent e){thisMouseClicked(e);}});
//hcanedo_21_09_2004_end
    }
    public void update()
    {
        m_cmStructureView.deleteAllViews();
       // m_cmStructureView.getM_TDStructure().deleteId(CMIndexTDStructureUpdate.getInstance().getIndex());
		m_cmStructureView.addCMStructureViews(m_cmStructureView.getM_TDStructure().getM_StructureTestData());
    }
    public void update(int index)
    {
        m_cmStructureView.deleteAllViews();
       // m_cmStructureView.getM_TDStructure().deleteId(CMIndexTDStructureUpdate.getInstance().getIndex());
		m_cmStructureView.addCMStructureViews(m_cmStructureView.getM_TDStructure().getM_StructureTestData(), index);
    }
	public void updateAll()
    {
        m_cmStructureView.deleteAllViews();
        m_cmStructureView.getM_TDStructure().deleteIds();
		m_cmStructureView.addCMStructureViews(m_cmStructureView.getM_TDStructure().getM_StructureTestData());
    }
	public void deleteAllViews()
    {
        m_cmStructureView.deleteAllViews();
    }
    public TDStructure getM_TDStructure(){ return m_TDStructure; }

    public void setM_TDStructure(TDStructure testData){
        this.m_TDStructure = m_TDStructure;
        m_cmStructureView.setM_TDStructure(testData);
    }

    //fcastro_01092004_begin
    public CMStructureView getM_cmStructureView(){
        return m_cmStructureView;
    }
    //fcastro_01092004_end
	public void setAccessRights(boolean right){
        m_cmStructureView.setAccessRights(right);
    }
//hcanedo_21_09_2004_begin
    public void thisMouseClicked(MouseEvent e) {
		m_Frame.eventMouseClicked(null);
    }
//hcanedo_21_09_2004_end
    private CMFrameView m_Frame;
    private CMStructureView m_cmStructureView;
    private CMStructureHeaderView m_CMStructureHeaderView;
    private JSmartGridHeader m_GridHeader;
    private TDStructure m_TDStructure;
}
