/* Generated by Together */

package bi.view.testdataviews;
import com.eliad.model.defaults.DefaultStyleModel;
import com.eliad.model.defaults.DefaultGridCellRenderer;
import javax.swing.JLabel;

public class CMStyleModelHeader extends DefaultStyleModel {
        public CMStyleModelHeader() {
            ((DefaultGridCellRenderer)this.getRenderer(String.class)).setHorizontalAlignment(JLabel.LEFT);
        }

 /*       /////////////////////////////////////////////////////////////////////////////
        public class CMCellRenderer extends DefaultGridCellRenderer {
            public CMCellRenderer() {

            }

            public Component getComponent(Object value, boolean isSelected, boolean hasFocus, boolean isEditable, int row,
                int column, GridContext context) {
                    Component c = super.getComponent(value, isSelected, hasFocus, isEditable, row, column, context);
                    Object obj = m_Model.getCellObjectAt(row, column);
                    if (obj instanceof CMCellHeaderTDStructureName || obj instanceof CMCellHeaderTDStructureType ||
                        obj instanceof CMCellHeaderTDStructureLength || obj instanceof CMCellHeaderTDStructurePrefix ||
                        obj instanceof CMCellHeaderTDStructureSuffix || obj instanceof CMCellHeaderTDStructureFormula ||
                        obj instanceof CMCellHeaderTDStructureValue || obj instanceof CMCellHeaderTDStructureFormat ||
                        obj instanceof CMCellHeaderTDStructureField || obj instanceof CMCellHeaderTDStructureKey ||
                        obj instanceof CMCellHeaderTDStructureGlobal) {
                            c.setBackground(new Color(36, 38, 116));
                            c.setForeground(new Color(252, 254, 252));
                            this.setHorizontalAlignment(JLabel.LEFT);
                            c.setFont(new Font("Dialog", Font.PLAIN, 12)); //$NON-NLS-1$
                            if (!isSelected) {
                                this.setBorder(BorderFactory.createRaisedBevelBorder());
                            }
                    }
                    else {
                        if(cmFrame.isIsPanelTestDataSelected())
                        {
	                       	if (obj instanceof CMCellTDStructureName || obj instanceof CMCellTDStructureClassState ||
    	                    obj instanceof CMCellTDStructureLength || obj instanceof CMCellTDStructurePrefix ||
        	                obj instanceof CMCellTDStructureSuffix ||  obj instanceof CMCellTDStructureFormat ||
                	        obj instanceof CMCellTDStructureField || obj instanceof CMCellTDStructureKey ||
                    	    obj instanceof CMCellTDStructureGlobal) {
								c.setBackground(new Color(235, 235, 228));
                           }
                           else
                           {
                            c.setBackground(new Color(255,255,255));
                           }
                        }
                        else
                        {
                            c.setBackground(new Color(255, 255, 255));
                        }
                       // c.setBackground(new Color(235, 235, 228));
                    }
                    return c;
            }
        }
 */
}
