/* Generated by Together */

package bi.view.testdataviews;
import com.eliad.swing.DefaultHeaderModel;
import com.eliad.swing.JSmartGrid;

import bi.view.lang.CMMessages;

public class CMStructureHeaderView extends DefaultHeaderModel {
	 final int colCount = 3;
      final String[] colNames = {CMMessages.getString("TESTDATA_STRUCTURE"),CMMessages.getString("TESTDATA_TYPE"),CMMessages.getString("TESTDATA_DESCRIPTION")}; //$NON-NLS-1$ //$NON-NLS-2$ //$NON-NLS-3$

      public CMStructureHeaderView(JSmartGrid jSmartGrid) {
        super(jSmartGrid, JSmartGrid.HORIZONTAL);
        initGUI();
      }

      public void initGUI(){
               
      }

      public int getRowCount() {
        return 1;
      }
      public int getColumnCount() {
        return colCount;
      }
      public Object getValueAt(int row, int column) {
        return colNames[column];
      }

}
