/* Generated by Together */

package bi.view.undomanagementviews.undotestdataviews;

import javax.swing.undo.CannotRedoException;
import javax.swing.undo.CannotUndoException;
import javax.swing.undo.UndoableEdit;

import model.ITypeData;
import bi.view.mainframeviews.CMFrameView;
import bi.view.testdataviews.CMGridTDStructure;
import bi.view.testdataviews.CMPanelTestDataView;
import bi.view.undomanagementviews.CMCompoundEdit;
import bi.view.undomanagementviews.undoviews.CMComponentAwareEdit;
import bi.view.undomanagementviews.undoviews.CMUndoMediator;

public class CMEditInValidGlobalReferenceAndFormulainTestData extends CMComponentAwareEdit {
    private CMPanelTestDataView m_CMPanelTestDataView;
    private CMGridTDStructure m_CMGridTDStructure;
    private int m_IndexTestData;
    private int m_indexStructure;
    private ITypeData m_NewTypeData;
    private ITypeData m_OldtypeData;
    private int m_numoftable;
    private int m_numofrow;
    private int m_row;
    private int m_column;
    private CMCompoundEdit m_ce;

    public CMEditInValidGlobalReferenceAndFormulainTestData(CMFrameView p_CMFrameView,
        CMPanelTestDataView p_CMPanelTestDataView, CMGridTDStructure p_CMGridTDStructure, int p_IndexTestData,
        int p_indexStructure, ITypeData p_OldTypeData, ITypeData p_NewTypeData, int p_numoftable, int p_numofrow, int p_row,
        int p_column, CMUndoMediator.FocusInfo p_FocusInfo, UndoableEdit p_ce) {
            super(p_FocusInfo, p_CMFrameView);
            this.m_CMGridTDStructure = p_CMGridTDStructure;
            this.m_CMPanelTestDataView = p_CMPanelTestDataView;
            this.m_IndexTestData = p_IndexTestData;
            this.m_indexStructure = p_indexStructure;
            this.m_OldtypeData = p_OldTypeData;
            this.m_NewTypeData = p_NewTypeData;
            this.m_numoftable = p_numoftable;
            this.m_numofrow = p_numofrow;
            this.m_row = p_row;
            this.m_column = p_column;
            m_ce = (CMCompoundEdit) p_ce;
    }

    public void redo() throws CannotUndoException {
        super.redo();
    	if(this.m_ce.isInProgress()){
    		m_ce.endAll();
    	}
    	this.m_ce.redo();
        //ITypeData aux = (ITypeData)m_NewTypeData.clone();
        //m_CMPanelTestDataView.undoRedoInValidGlobalAndFormulaInTestData(m_IndexTestData, m_indexStructure, m_row, m_column,
            //m_indexStructure, (ITypeData)m_NewTypeData.clone());
        //int globalindex = m_CMPanelTestDataView.undoGlobalReferenceinTestData(m_IndexTestData,
            //m_indexStructure, m_row, m_column, aux);
        //m_CMGridTDStructure.ifcancelReferenceInTestDataCancelinStructure(globalindex, m_row - 1);
        m_CMPanelTestDataView.update(m_IndexTestData, m_indexStructure);
        int n = m_CMFrameView.getM_CMUndoMediator().getM_NumberOfUndoableEditObjects() + 1;
        m_CMFrameView.getM_CMUndoMediator().setM_NumberOfUndoableEditObjects(n);
        int m = m_CMFrameView.getM_CMUndoMediator().getM_NumberOfRedoableEditObjects() - 1;
        m_CMFrameView.getM_CMUndoMediator().setM_NumberOfRedoableEditObjects(m);
		 this.m_CMPanelTestDataView.getM_CMGridTDStructure().setRowSelected(m_row);
		 this.m_CMPanelTestDataView.getM_CMGridTDStructure().setColumnSelected(m_column);
		 this.m_CMPanelTestDataView.getM_CMGridTDStructure().changeSelection(m_row,m_column,false,false);
		 this.m_CMPanelTestDataView.getM_CMGridTDStructure().grabFocus();
        setUndoState();
        setRedoState();
    }

    public void undo() throws CannotRedoException {
        super.undo();
    	if(this.m_ce.isInProgress()){
    		m_ce.endAll();
    	}
    	this.m_ce.undo();
/*        if(m_OldtypeData.getGlobal().equals("G")){
        	ITypeData m_typ = m_CMGridTDStructure.setGlobalReferenceStructure(m_numoftable, m_numofrow,null);
        }
        m_CMPanelTestDataView.undoRedoInValidGlobalAndFormulaInTestData(m_IndexTestData, m_indexStructure, m_row, m_column,
            m_indexStructure, (ITypeData)m_OldtypeData.clone());*/
        m_CMPanelTestDataView.update(m_IndexTestData, m_indexStructure);
        int n = m_CMFrameView.getM_CMUndoMediator().getM_NumberOfUndoableEditObjects() - 1;
        m_CMFrameView.getM_CMUndoMediator().setM_NumberOfUndoableEditObjects(n);
        int m = m_CMFrameView.getM_CMUndoMediator().getM_NumberOfRedoableEditObjects() + 1;
        m_CMFrameView.getM_CMUndoMediator().setM_NumberOfRedoableEditObjects(m);
		 this.m_CMPanelTestDataView.getM_CMGridTDStructure().setRowSelected(m_row);
		 this.m_CMPanelTestDataView.getM_CMGridTDStructure().setColumnSelected(m_column);
		 this.m_CMPanelTestDataView.getM_CMGridTDStructure().changeSelection(m_row,m_column,false,false);
		 this.m_CMPanelTestDataView.getM_CMGridTDStructure().grabFocus();
        setUndoState();
        setRedoState();

    }
}

/* This Software has been developed by Business Software Innovations  .
Copyright (c)2003 Díaz und Hilterscheid Unternehmensberatung. All rights reserved. */
