/* Generated By:JavaCC: Do not edit this line. VisioImportConstants.java */
package bi.view.businessrulesviews.brimport.visioparser;

public interface VisioImportConstants {

  int EOF = 0;
  int BEGINPAGE = 7;
  int ENDPAGE = 8;
  int PAGENAME = 9;
  int DOTS = 10;
  int SEMICOLON = 11;
  int BEGININISTATE = 12;
  int ENDINISTATE = 13;
  int TYPE = 14;
  int BEGINFINALSTATE = 15;
  int ENDFINALSTATE = 16;
  int ID = 17;
  int BEGINSTATE = 18;
  int ENDSTATE = 19;
  int BUSINESSACTION = 20;
  int EQUALS = 21;
  int BEGINTRANSITION = 22;
  int ENDTRANSITION = 23;
  int TRANSITION = 24;
  int BEGIN = 25;
  int END = 26;
  int NUMBER = 27;
  int QUOTES = 28;
  int VALUES = 29;
  int BEGINCONSTRAINT = 30;
  int ENDCONSTRAINT = 31;
  int BEGINRELATION = 32;
  int ENDRELATION = 33;
  int STATECONSTRAINT = 34;
  int RISKLEVELCONSTRAINT = 35;
  int REQUIREMENTSCONSTRAINT = 36;
  int RESULTCONSTRAINT = 37;
  int STATEVALUE = 38;
  int OPENBRACKET = 39;
  int CLOSEBRACKET = 40;
  int COMMA = 41;
  int STRINGS = 42;

  int DEFAULT = 0;

  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\t\"",
    "\"\\n\"",
    "\"\\r\"",
    "\"\\f\"",
    "\"\\r\\n\"",
    "\"Begin_Page\"",
    "\"End_Page\"",
    "\"Page_Name\"",
    "\":\"",
    "\";\"",
    "\"Begin_InitialState\"",
    "\"End_InitialState\"",
    "\"Type\"",
    "\"Begin_FinalState\"",
    "\"End_FinalState\"",
    "\"ID\"",
    "\"Begin_State\"",
    "\"End_State\"",
    "\"Business Action\"",
    "\"=\"",
    "\"Begin_Transition\"",
    "\"End_Transition\"",
    "\"Transition\"",
    "\"Begin\"",
    "\"End\"",
    "<NUMBER>",
    "\"\\\"\"",
    "<VALUES>",
    "\"Begin_Constraint\"",
    "\"End_Constraint\"",
    "\"Begin_Relation\"",
    "\"End_Relation\"",
    "\"STATE\"",
    "\"RISK LEVEL\"",
    "\"REQUIREMENTS\"",
    "\"RESULT\"",
    "<STATEVALUE>",
    "\"{\"",
    "\"}\"",
    "\",\"",
    "<STRINGS>",
  };

}
