/* Generated By:JavaCC: Do not edit this line. RequirementResultValuesConstants.java */
package bi.controller.brparser.requirementsresultparser;

public interface RequirementResultValuesConstants {

  int EOF = 0;
  int COMA = 5;
  int VALUE = 6;
  int EQUAL = 7;
  int STRING = 8;

  int DEFAULT = 0;

  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\t\"",
    "\"\\n\"",
    "\"\\r\"",
    "\",\"",
    "<VALUE>",
    "\"=\"",
    "<STRING>",
  };

}
