/* Generated by Together */

package model;

public class TestDataSet implements Cloneable {
    public TestDataSet(TDStructure p_TDStructure)
    {
	//	m_TDStructure= p_TDStructure;
        m_TestDataCombinations = new TestDataCombinations();
        description=""; //$NON-NLS-1$
        name= generateName(p_TDStructure);
    }
    public Object clone() {
      Object b = null;
      try {
       b = super.clone();
      } catch(CloneNotSupportedException e) {
        e.printStackTrace();
      }
      return b;
    }
	public TestDataSet cloneTestDataSet(){
		 Object b = null;

       		b=clone();
            TestDataSet newTestDataSet=(TestDataSet) b;
            newTestDataSet.setM_TestDataCombinations(newTestDataSet.getM_TestDataCombinations().cloneTestDataCombinations());
      return (TestDataSet)b;
    }
//    public TDStructure getM_TDStructure(){ return m_TDStructure; }

//    public void setM_TDStructure(TDStructure m_TDStructure){ this.m_TDStructure = m_TDStructure; }

    public String getName(){ return name; }

    public void setName(String name){ this.name = name; }

    public String getDescription(){ return description; }

    public void setDescription(String description){ this.description = description; }

    public TestDataCombinations getM_TestDataCombinations(){ return m_TestDataCombinations; }

    public void setM_TestDataCombinations(TestDataCombinations m_TestDataCombinations){ this.m_TestDataCombinations = m_TestDataCombinations; }
	 public String generateName(TDStructure m_TDStructure)
     {
       int id= m_TDStructure.generateIdTestDataSet();
       this.setId(id);
      StringBuffer idString = new StringBuffer();
      idString.append(id);
      int length = idString.length();
        for(int i = 0; i < BusinessRules.ID_LENGTH-length; i++) {
          idString.insert(0,BusinessRules.ID_FILLER_CHARACTER);
        }
      idString.insert(0,BusinessRules.TESTDATASET_PREFIX);
      return  idString.toString();
    }

    public String getM_ReportFormat(){
        if(m_ReportFormat == null || m_ReportFormat.equals(""))
        {
            m_ReportFormat=BusinessRules.REPORT_XSLT_DEFAULT;
        }
        return m_ReportFormat;
    }

    public void setM_ReportFormat(String m_ReportFormat){ this.m_ReportFormat = m_ReportFormat; }

    public int getId(){
            return id;
        }

    public void setId(int id){
            this.id = id;
        }

 //   private TDStructure m_TDStructure;
    private String name;
    private String description;
    private TestDataCombinations m_TestDataCombinations;
    private String m_ReportFormat=BusinessRules.REPORT_XSLT_DEFAULT;
    private int id;
}
