/* Generated by Together */

package model;

import javax.swing.undo.UndoableEdit;

import model.edit.CMModelEditFactory;
import bi.view.undomanagementviews.CMCompoundEdit;
public class TestData implements Cloneable {
    public TestData(TDStructure p_TDStructure) {
         setM_TDStructure(p_TDStructure);
       //  setM_TestDataCombination(p_TDStructure.getTestDataCombination());
        setSet(false);
        setM_TestCaseinTestData(""); //$NON-NLS-1$
        setDescription(""); //$NON-NLS-1$
        setName("");//generateName(p_TDStructure.getTestDataCombination()));
        setContTestDataSet(0);
        setM_RiskLevel(0);
    }

    public String getM_TestCaseinTestData(){
    	if(m_TestCaseinTestData == null)
    		m_TestCaseinTestData = "";
    	return m_TestCaseinTestData; }

    public void setM_TestCaseinTestData(String m_TestCaseinTestData){ this.m_TestCaseinTestData = m_TestCaseinTestData; }

  //  public TestDataCombinations getM_TestDataCombination(){ return m_TestDataCombination; }

  //  public void setM_TestDataCombination(TestDataCombinations m_TestDataCombination){ this.m_TestDataCombination = m_TestDataCombination; }

    public boolean isSet(){ return set; }

    public void setSet(boolean set){ this.set = set; }

    public String getDescription(){
    	if(description == null)
    		description = "";
    	return description; }

    public void setDescription(String description){ this.description = description; }

   public TDStructure getM_TDStructure(){
	   if(m_TDStructure == null)
		   m_TDStructure = new TDStructure();
	   return m_TDStructure; }

 public void setM_TDStructure(TDStructure m_TDStructure){ this.m_TDStructure = m_TDStructure; }

    public String getName(){
    	if(name == null)
    		name = "";
    	return name; }

    public void setName(String name){ this.name = name; }

    public String generateName(TDStructure tdStructure,UndoableEdit p_ce) {
    	CMCompoundEdit ce;
    	if(p_ce == null)
    		//ce = new CMCompoundEdit(2000);
    		ce = new CMCompoundEdit();
    	else
    		ce = (CMCompoundEdit) p_ce;
       int id;

		id = tdStructure.generateIdTestData(ce);

       ce.addEdit(CMModelEditFactory.INSTANCE.createChangeIdInTestDataModelEdit(this,id));
       this.setId(id);
      StringBuffer idString = new StringBuffer();
      idString.append(id);
      int length = idString.length();
        for(int i = 0; i < BusinessRules.ID_LENGTH+1-length; i++) {
          idString.insert(0,BusinessRules.ID_FILLER_CHARACTER);
        }
      idString.insert(0,BusinessRules.TESTDATA_PREFIX);
      return  idString.toString();
    }
    /*******************************************************************************/
    /*nuevos metodos para la importacion 										   */
    /*******************************************************************************/
    public String generateNameSpecificID(int p_id)
    {
        this.setId(p_id);
      StringBuffer idString = new StringBuffer();
      idString.append(p_id);
      int length = idString.length();
        for(int i = 0; i < BusinessRules.ID_LENGTH+1-length; i++) {
          idString.insert(0,BusinessRules.ID_FILLER_CHARACTER);
        }
      idString.insert(0,BusinessRules.TESTDATA_PREFIX);
      return  idString.toString();
    }
    /*******************************************************************************/
     public String generateDescription()
     {
		String res = BusinessRules.DESCRIPTION_TESTDATA;
		return res;
     }

    public int getContTestDataSet(){
            return contTestDataSet;
        }

    public void setContTestDataSet(int contTestDataSet){
            this.contTestDataSet = contTestDataSet;
        }

    public int getId(){
            return id;
        }

    public void setId(int id){
            this.id = id;
        }

		public Object clone() {
      Object b = null;
      try {
       b = super.clone();
      } catch(CloneNotSupportedException e) {
        e.printStackTrace();
      }
      return b;
    }
    public TestData cloneTestData()
    {
         Object b = null;
       		b = clone();
            TestData newTestData=(TestData) b;
            newTestData.setM_TDStructure((TDStructure)newTestData.getM_TDStructure().clone());
      return (TestData)b;
    }

    public int getM_RiskLevel() {
      return m_RiskLevel;
    }

    public void setM_RiskLevel(int p_RiskLevel){
      m_RiskLevel = p_RiskLevel;
    }

    private String m_TestCaseinTestData;
  //  private TestDataCombinations m_TestDathjgfjhgjhgjghjghjghjghjghgjghbination;
    private boolean set;
    private String description;
    private TDStructure m_TDStructure;
    private String name;
    private int contTestDataSet;
    private int id;
    //grueda20092004_begin
    private int m_RiskLevel = 0;
    //grueda20092004_end
}
