/* Generated by Together */

package  bi.view.cells;

import com.eliad.swing.JSmartGrid;

public class CMCellHeaderTDStructureType extends CMCellTDStructure {
	public CMCellHeaderTDStructureType(JSmartGrid p_grid, Object p_model) {
		super(p_grid, p_model);
		//set the default renderer for this 
		this.setRenderer(defaultGridHeaderRenderer);
	}

	public String getName(){ return name; }
    
    public String toString() {
    	return name;
    }

    public void setName(String name){ this.name = name; }

    private String name = "Type";//CMMessages.getString("LABEL_DESCRIPTION");    

}
