/* Generated by Together */

package  bi.view.cells;

import java.util.Vector;
public class CMCellGroupHeaderTDStructure extends Vector {
    public CMCellGroupHeaderTDStructure(int num) {
        super(num);
    }
}
