/* Generated by Together */

package  bi.view.cells;

import bi.view.cells.renderers.CMCellHeaderTDStructureRenderer;
import com.eliad.model.defaults.DefaultGridCellRenderer;
import com.eliad.swing.JSmartGrid;
import model.TDStructure;

public class CMCellTDStructure extends CMBaseCell {
	public CMCellTDStructure(JSmartGrid p_grid, Object p_model) {
		super(p_grid, p_model);
		
	}
   
    public static final DefaultGridCellRenderer defaultGridHeaderRenderer = new CMCellHeaderTDStructureRenderer();
    
    public TDStructure getTDStructure(){ return (TDStructure)getModel(); }

    public void setTDStructure(TDStructure testData){ setModel(testData); }
    
   
	//////////
   /* public CMCellTDStructure(TDStructure m_testData) {
        testData = m_testData;
    }

    public TDStructure getTDStructure(){ return testData; }

    public void setTDStructure(TDStructure testData){ this.testData = testData; }

    private TDStructure testData;*/
}
