/* Generated by Together */

package  bi.view.cells;

import java.util.Vector;
public class CMCellGroupDataTDStructure extends Vector {
    public CMCellGroupDataTDStructure(int num) {
        super(num);
    }
}
