/* Generated by Together */

package  bi.view.cells;

import model.ReportRecord;

import com.eliad.swing.JSmartGrid;

public class CMFilePathCell extends CMBaseCell{
   
    public CMFilePathCell(JSmartGrid p_grid, ReportRecord p_model) {
    	super(p_grid, p_model);
    }
    
    public CMReportOutputView getM_CMReportOutputView(){ return m_CMReportOutputView; }

    public void setM_CMReportOutputView(CMReportOutputView m_CMReportOutputView){ this.m_CMReportOutputView = m_CMReportOutputView; }
    
    private CMReportOutputView m_CMReportOutputView;
    
    //ccastedo begins 31.08.06
    @Override
    public String toString() {   
    	return ((ReportRecord)getModel()).getM_Path();   
    }
//    //ccastedo ends 31.08.06
}
