/* Generated by Together */

package  bi.view.cells;

public class CMReportNameCell {
    public CMReportNameCell() {
    }

    public String getValue(){ return value; }

    public void setValue(String value){ this.value = value; }

    public CMReportOutputView getM_CMReportOutputView(){ return m_CMReportOutputView; }

    public void setM_CMReportOutputView(CMReportOutputView m_CMReportOutputView){ this.m_CMReportOutputView = m_CMReportOutputView; }

    private String value;
    private CMReportOutputView m_CMReportOutputView;
}
