/* Generated by Together */

package  bi.view.cells;

public class CMTestDataSetCellReportFormat {
    public CMTestDataSetCellReportFormat() {
    }

    public CMTestDataSetGroup getM_CMTestDataSetGroup(){ return m_CMTestDataSetGroup; }

    public void setM_CMTestDataSetGroup(CMTestDataSetGroup m_CMTestDataSetGroup){ this.m_CMTestDataSetGroup = m_CMTestDataSetGroup; }
    public String toString()
    {
		return name;
    }

    public String getName(){ return name; }

    public void setName(String name){ this.name = name; }

    private CMTestDataSetGroup m_CMTestDataSetGroup;
    private String name;
}
