/* Generated by Together */

package  bi.view.cells;

import java.util.Vector;

import model.TestData;
public class CMTestDataCombinationGroup extends Vector {
    public CMTestDataCombinationGroup(TestData p_testData ) {
        	super(0);
        	m_TestData = p_testData;
    }

    public CMTestDataCombinationCellName getM_CMTestDataCombinationCellName(){ return m_CMTestDataCombinationCellName; }

    public void setM_CMTestDataCombinationCellName(CMTestDataCombinationCellName m_CMTestDataCombinationCellName){ this.m_CMTestDataCombinationCellName = m_CMTestDataCombinationCellName; }

    public CMTestDataCombinationCellTestCase getM_CMTestDataCombinationCellTestCase(){ return m_CMTestDataCombinationCellTestCase; }

    public void setM_CMTestDataCombinationCellTestCase(CMTestDataCombinationCellTestCase m_CMTestDataCombinationCellTestCase){ this.m_CMTestDataCombinationCellTestCase = m_CMTestDataCombinationCellTestCase; }

    public CMTestDataCombinationCellSet getM_CMTestDataCombinationCellSet(){ return m_CMTestDataCombinationCellSet; }

    public void setM_CMTestDataCombinationCellSet(CMTestDataCombinationCellSet m_CMTestDataCombinationCellSet){ this.m_CMTestDataCombinationCellSet = m_CMTestDataCombinationCellSet; }

    public CMTestDataCombinationCellDescription getM_CMTestDataCombinationCellDescription(){ return m_CMTestDataCombinationCellDescription; }

    public void setM_CMTestDataCombinationCellDescription(CMTestDataCombinationCellDescription m_CMTestDataCombinationCellDescription){ this.m_CMTestDataCombinationCellDescription = m_CMTestDataCombinationCellDescription; }

    public CMTestDataCombinationCellRiskLevel getM_CMTestDataCombinationCellRiskLevel(){ return m_CMTestDataCombinationCellRiskLevel; }

    public void setM_CMTestDataCombinationCellRiskLevel(CMTestDataCombinationCellRiskLevel m_CMTestDataCombinationCellRiskLevel){ this.m_CMTestDataCombinationCellRiskLevel = m_CMTestDataCombinationCellRiskLevel; }

    public TestData getM_TestData(){ return m_TestData; }

    public void setM_TestData(TestData m_TestData){ this.m_TestData = m_TestData; }

    /**
     * @link aggregationByValue 
     */
    private CMTestDataCombinationCellName m_CMTestDataCombinationCellName;
	 /**
     * @link aggregationByValue 
     */
    
    private CMTestDataCombinationCellTestCase m_CMTestDataCombinationCellTestCase;

    /**
     * @link aggregationByValue 
     */
    private CMTestDataCombinationCellSet m_CMTestDataCombinationCellSet;

    /**
     * @link aggregationByValue 
     */
    private CMTestDataCombinationCellDescription m_CMTestDataCombinationCellDescription;

    /**
     * @link aggregationByValue 
     */
    private CMTestDataCombinationCellRiskLevel m_CMTestDataCombinationCellRiskLevel;
    private TestData m_TestData;
}
