/* Generated by Together */

package  bi.view.cells;

public class CMTestDataSetCellFilePathReportFormat {
    public CMTestDataSetCellFilePathReportFormat() {
    }

    public CMTestDataSetGroup getM_CMTestDataSetGroup(){ return m_CMTestDataSetGroup; }

    public void setM_CMTestDataSetGroup(CMTestDataSetGroup m_CMTestDataSetGroup){ this.m_CMTestDataSetGroup = m_CMTestDataSetGroup; }

    private CMTestDataSetGroup m_CMTestDataSetGroup;
}
