/* Generated by Together */

package  bi.view.cells;

public class CMTestDataCombinationCellSet {
    public CMTestDataCombinationCellSet() {
    }

    public CMTestDataCombinationGroup getM_CMTestDataCombinationGroup(){ return m_CMTestDataCombinationGroup; }

    public void setM_CMTestDataCombinationGroup(CMTestDataCombinationGroup m_CMTestDataCombinationGroup){ this.m_CMTestDataCombinationGroup = m_CMTestDataCombinationGroup; }

    private CMTestDataCombinationGroup m_CMTestDataCombinationGroup;
}
