/* Generated By:JavaCC: Do not edit this line. AmericanParserConstants.java */
package bi.controller.tdparser.american;

public interface AmericanParserConstants {

  int EOF = 0;
  int Variable = 7;
  int MAY = 8;
  int MEN = 9;
  int IGUAL = 10;
  int MAYIGUAL = 11;
  int MENIGUAL = 12;
  int DIF = 13;
  int DIFALT = 14;
  int BRACKETOPEN = 15;
  int BRACKETCLOSE = 16;
  int PARTOPEN = 17;
  int PARTCLOSE = 18;
  int AND = 19;
  int INTEGER = 20;
  int REALNUMBER = 21;
  int NEGNUMBER = 22;
  int NUMBER = 23;
  int MILES = 24;
  int PARTMIL = 25;
  int DIGIT = 26;
  int SIGNEG = 27;
  int POINT = 28;
  int COMA = 29;
  int STRINGS = 30;

  int DEFAULT = 0;

  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\t\"",
    "\"\\n\"",
    "\"\\r\"",
    "\"\\f\"",
    "\"\\r\\n\"",
    "\"$\"",
    "\">\"",
    "\"<\"",
    "\"=\"",
    "<MAYIGUAL>",
    "<MENIGUAL>",
    "<DIF>",
    "<DIFALT>",
    "\"[\"",
    "\"]\"",
    "\"(\"",
    "\")\"",
    "<AND>",
    "<INTEGER>",
    "<REALNUMBER>",
    "<NEGNUMBER>",
    "<NUMBER>",
    "<MILES>",
    "<PARTMIL>",
    "<DIGIT>",
    "\"-\"",
    "\".\"",
    "\",\"",
    "<STRINGS>",
  };

}
